# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  spack-build:
    name: '[spack:Tags:${{ matrix.project_tags }}@${{ matrix.docker_image }}@${{ matrix.build_type }}]'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        cmake_generator:
          - "Ninja"
        docker_image:
          - "ubuntu:jammy"
        project_tags:
          - v2023.02.3
          - master

    container:
      image: ${{ matrix.docker_image }}

    steps:
    #- uses: actions/checkout@master

    - name: System Dependencies [apt]
      run: |
        apt-get -y update
        apt-get -y install git python3 build-essential curl tar gzip unzip bzip2 gnupg2 xz-utils
    - name: Check free space
      run: |
        df -h

    - name: Install Spack 
      run: |
        git clone https://github.com/spack/spack -b v0.19.2
        . spack/share/spack/setup-env.sh

    - name: Dependencies [Spack]
      run: |
        . spack/share/spack/setup-env.sh
        # See https://spack.readthedocs.io/en/latest/replace_conda_homebrew.html
        spack env create robsubenv
        spack -e robsubenv add ace gsl ipopt libedit eigen libjpeg-turbo cmake pkg-config opencv spdlog qhull python swig py-pybind11 nlohmann-json tinyxml tinyxml2 sqlite matio assimp
        spack -e robsubenv concretize
        spack -e robsubenv install
        spack env activate robsubenv

    - name: Check free space
      run: |
        df -h

    - name: Download, Configure and Build [Spack]
      run: |
        . spack/share/spack/setup-env.sh
        spack env activate robsubenv
        git clone https://github.com/robotology/robotology-superbuild -b  ${{ matrix.project_tags }}
        cd robotology-superbuild
        mkdir build
        cd build
        cmake -DROBOTOLOGY_ENABLE_CORE:BOOL=ON  -DROBOTOLOGY_ENABLE_ICUB_HEAD:BOOL=ON  -DROBOTOLOGY_USES_GAZEBO:BOOL=OFF -DNON_INTERACTIVE_BUILD:BOOL=ON ..
        cmake --build . --config ${{ matrix.build_type }}

    - name: Check free space
      run: |
        df -h
